import {
  pgTable,
  text,
  uuid,
  boolean,
  integer,
  timestamp,
  index,
  unique,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";
import { organizations } from "./org";
import { users } from "../schema";

/**
 * Calendar events. See docs/work-log/2026-08-26-events-model.md (Phase 3) and
 * DECISION-113/115.
 *
 * One flat table, one row per discrete occurrence — never a template/instance
 * split, never RRULE. A repeating series is N materialized rows sharing
 * `parentEventId`, generated by a ported convenience function at create time;
 * `recurrencePattern` is a display/regeneration string, NEVER parsed at read
 * time (DECISION-113 ruling 1). `organizationServiceTimes` (src/lib/db/domain/
 * sites.ts) answers "what time is it, every week, forever" for the public-site
 * header; this table answers "what's on the calendar" — neither writes the
 * other (DECISION-113 ruling 2).
 *
 * Occurrence times are wall-clock local (`timestamp` without time zone, no
 * org-timezone column exists per D6/US-only scope) so a stored "7:00 PM"
 * survives a DST transition with no extra machinery (DECISION-113 ruling 3).
 * `cancelledAt` is the one legitimate `timestamptz` column here — an instant,
 * not a schedule fact.
 *
 * The six columns `id`/`organizationId`/`startsAt`/`endsAt`/`cancelledAt`/
 * `allowsCheckin` are FROZEN for the children's-ministry check-in contract
 * (DECISION-113 ruling 4) — its own FK must be the composite
 * `(event_id, organization_id)` against `eventsIdOrgKey` below. No other
 * column may be added to, renamed on, or removed from that set without a
 * joint re-review of both pipelines.
 */
export const events = pgTable(
  "events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: uuid("organization_id")
      .notNull()
      .references(() => organizations.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    description: text("description"),
    location: text("location"),
    // Wall-clock local time, no tz (DECISION-113 ruling 3) — matches
    // organizationServiceTimes' existing time-of-day columns in spirit.
    startsAt: timestamp("starts_at").notNull(),
    endsAt: timestamp("ends_at"),
    isPublic: boolean("is_public").notNull().default(true),
    // The FROZEN check-in contract column (DECISION-113 ruling 4). Adopted
    // name over fpcw's `is_drop_off` — generic beyond children's ministry.
    // Children's-ministry Increment C's FK must be the composite
    // (event_id, organization_id) against events_id_org_key below.
    allowsCheckin: boolean("allows_checkin").notNull().default(false),
    // The one legitimate timestamptz column (an instant, not a schedule
    // fact) — DECISION-113 ruling 3's own carve-out.
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    // Self-referential, standard Drizzle explicit-return-type idiom to break
    // TS circularity (`(): AnyPgColumn => events.id`). Deliberately NOT a
    // composite (id, organizationId) self-FK — architect's Phase 2 ruling
    // that a self-referencing composite FK is not expressible here without
    // circularity, the same class as groups' own derived-check. The same-org
    // property is enforced entirely at the application layer (see src/lib/
    // events.ts's "Same-org parent guard") — an accepted, narrow deviation
    // from Composite Tenant Keys, same class as
    // groupMemberships.officerTermId (DECISION-060), flagged here rather
    // than silently accepted.
    parentEventId: uuid("parent_event_id").references(
      (): AnyPgColumn => events.id,
    ),
    // Convenience generation string only (e.g. "weekly", "2nd Tuesday") —
    // NEVER parsed at read time (DECISION-113 ruling 1). Set ONLY on a
    // series' first (parent) row; null on every generated child and on every
    // standalone event.
    recurrencePattern: text("recurrence_pattern"),
    // The count last used to generate this series — read back by
    // extendSeriesPattern to compute the series-total bounds check. Null on
    // a standalone event or a generated child.
    recurrenceCount: integer("recurrence_count"),
    createdBy: uuid("created_by").references(() => users.id),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (t) => [
    // Leading with organizationId per every tenant table's own convention.
    // Serves the admin list's own ordering.
    index("events_org_starts_idx").on(t.organizationId, t.startsAt),
    // Serves "load every occurrence in this series" (getEvent's sibling
    // list, extendSeriesPattern's latest-occurrence lookup).
    index("events_org_parent_idx").on(t.organizationId, t.parentEventId),
    unique("events_id_org_key").on(t.id, t.organizationId),
  ],
);
