/**
 * Refreshes the ER diagrams in docs/schema-design.md from the live Drizzle
 * schema. Run after any schema change: `npm run docs:erd`.
 *
 * Rewrites only the block between the ERD markers, so the surrounding prose is
 * never clobbered.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { buildSchemaDocs, buildErd } from "../src/lib/dev-docs";

const DOC = "docs/schema-design.md";
const START = "<!-- BEGIN GENERATED ERD -->";
const END = "<!-- END GENERATED ERD -->";

const tables = buildSchemaDocs();
const modules = [...new Set(tables.map((t) => t.module))]
  .filter((m) => m !== "platform (from starter)")
  .sort();

const body = modules
  .map((m) => `### ${m}\n\n\`\`\`mermaid\n${buildErd(tables, m)}\n\`\`\``)
  .join("\n\n");

const generated = [
  START,
  "",
  "_Generated by `npm run docs:erd` from `src/lib/db/schema`. Do not hand-edit._",
  "",
  body,
  "",
  END,
].join("\n");

const doc = readFileSync(DOC, "utf8");
const s = doc.indexOf(START);
const e = doc.indexOf(END);
if (s === -1 || e === -1) {
  console.error(`${DOC}: missing ERD markers`);
  process.exit(1);
}

writeFileSync(DOC, doc.slice(0, s) + generated + doc.slice(e + END.length));
console.log(`${DOC}: refreshed ${modules.length} diagrams from ${tables.length} tables`);
